baseURL = 'http://0.0.0.0:1313/11th-physics/'
title = '11th Physics'
theme = 'design-system'

# Needed for mermaid/katex shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[languages]
[languages.en]
title = '11th Physics'
languageName = 'English'
contentDir = 'content.en'
weight = 1

[languages.ta]
title = '11th இயற்பியல்'
languageName = 'தமிழ்'
contentDir = 'content.ta'
weight = 2
