# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"

          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "Only PRs from develop to main are allowed."
            exit 1
          fi
  call-workflow:
    # You must add these permissions so the called workflow can deploy
    permissions:
      contents: read
      id-token: write
      pages: write      # Required if deploying to GitHub Pages
    uses: gurukulams/design-system/.github/workflows/material-deploy.yml@main
    secrets: inherit # If the sub-workflow needs access to secrets