name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    permissions:
      contents: read
      id-token: write
      pages: write

    uses: gurukulams/design-system/.github/workflows/material-deploy.yml@main
    secrets: inherit